mutation CreateUserInvitation($input: CreateUserInvitationInput!) {
  createUserInvitation(input: $input) {
    ... on UserInvitation {
      id
    }
    ... on ApiCreateError {
      message
      errors {
        field
        message
      }
    }
  }
}
