mutation CreateUserInvitation($input: CreateUserInvitationInput!) {
  createUserInvitation(input: $input) {
    ... on UserInvitation {
      id
      catchment_district_ids
      email
      invitation_token
      organisation_id
      ttl
    }
    ... on ApiCreateError {
      message
      field
      value
    }
  }
}
