mutation DeleteUserInvitation($input: DeleteUserInvitationInput!) {
  deleteUserInvitation(input: $input) {
    ... on UserInvitation {
      id
    }
    ... on ApiDeleteError {
      message
      errors {
        field
        message
      }
    }
  }
}
