query GetDefaultUserDistrict($userId: ID!, $organisationUserId: ID!) {
  default_user_district(
    user_id: $userId
    organisation_user_id: $organisationUserId
  ) {
    ... on District {
      id
      name
      code
      province {
        ... on Province {
          id
          name
          code
          country {
            ... on Country {
              id
              name
              code
              flag
            }
          }
        }
      }
    }
  }
}
