query GetCurrentUser {
  me {
    ... on ApiNotFoundError {
      message
    }
    ... on User {
      id
      first_name
      last_name
      email
      user_districts {
        id
        roles
        is_default_user_district
        catchment_district {
          ... on CatchmentDistrict {
            id
            district {
              ... on District {
                id
                name
                province {
                  ... on Province {
                    id
                    name
                    country {
                      ... on Country {
                        id
                        code
                        flag
                        name
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      user_organisations {
        id
        is_default_organisation
        role
        organisation {
          ... on Organisation {
            id
            name
            logo
          }
        }
      }
    }
  }
}
