query GetCurrentUser {
  me {
    ... on ApiNotFoundError {
      message
    }
    ... on User {
      id
      first_name
      last_name
      email
      disabled
      user_organisations {
        id
        name
        logo
        is_user_default_organisation
        country {
          id
          name
        }
      }
      user_default_organisation {
        id
        name
        logo
        is_user_default_organisation
        users {
          id
          first_name
          last_name
          email
          disabled
          master_support
          organisation_id
          organisation_user_id
          role
          hashed_confirmation_token
          confirmed_at
          hashed_password_reset_token
          last_login
          theme
        }
        user_districts {
          id
          name
          code
          is_default_user_district
          catchment_district_id
          province {
            id
            name
            code
          }
        }
        country {
          code
          name
          flag
        }
      }
    }
  }
}
