mutation login($input: LoginInput!) {
  login(input: $input) {
    ... on ApiLoginError {
      message
      errors {
        field
        message
      }
    }
    ... on LoginSuccess {
      accessToken
      id
    }
  }
}
