query GetProvinces($countryId: ID!) {
  provinces(country_id: $countryId) {
    id
    name
    code
    created_at
    created_by
    last_modified_at
    last_modified_by
    country_id
    country {
      id
      name
      code
    }
    districts {
      id
      code
      name
    }
  }
}
