services:
  # Docker container for the database
  mis-database:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
# networks:
volumes:
  postgres: {}
# configs:
# secrets:
