export const provinces = [
  {
    code: "ZM-01",
    name: "Western",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-02",
    name: "Central",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-03",
    name: "Eastern",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-04",
    name: "Luapula",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-05",
    name: "Northern",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-06",
    name: "North-Western",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-07",
    name: "Southern",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-08",
    name: "Copperbelt",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-09",
    name: "Lusaka",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    code: "ZM-10",
    name: "Muchinga",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
];

export const districts = [
  {
    name: "Chililabombwe",
    code: "ZM-08-01",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Chingola",
    code: "ZM-08-02",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Kalulushi",
    code: "ZM-08-03",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Kitwe",
    code: "ZM-08-04",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Luanshya",
    code: "ZM-08-05",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Lufwanyama",
    code: "ZM-08-06",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Masaiti",
    code: "ZM-08-07",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Mpongwe",
    code: "ZM-08-08",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Mufulira",
    code: "ZM-08-09",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Ndola",
    code: "ZM-08-10",
    province_id: "ZM-08",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Chadiza",
    code: "ZM-03-01",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Chasefu",
    code: "ZM-03-02",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Chipangali",
    code: "ZM-03-03",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Chipata",
    code: "ZM-03-04",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Kasenengwa",
    code: "ZM-03-05",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Katete",
    code: "ZM-03-06",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Lumezi",
    code: "ZM-03-07",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Lundazi",
    code: "ZM-03-08",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Lusangazi",
    code: "ZM-03-09",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Mambwe",
    code: "ZM-03-10",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Nyimba",
    code: "ZM-03-11",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Petauke",
    code: "ZM-03-12",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Sinda",
    code: "ZM-03-13",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
  {
    name: "Vubwi",
    code: "ZM-03-14",
    province_id: "ZM-03",
    created_by: "chaiwa",
    last_modified_by: "chaiwa",
  },
];
